/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EmptyState: typeof import('./components/EmptyState/index.vue')['default']
    FormItem: typeof import('./components/FormItem/index.vue')['default']
    StatusTag: typeof import('./components/StatusTag/index.vue')['default']
    VisitCard: typeof import('./components/VisitCard/index.vue')['default']
  }
}
